export const themes = {
  got: {
    name: 'Game of Thrones',
    cards: ['arya', 'сersei', 'deyeneris', 'jaime', 'snow', 'tyrion'],
    imgPath: './src/img/',
    cardBack: '../img/card-back.jpg',
    boardMobile: '../img/board-mobile.jpg',
    board: '../img/board.jpg',
    cursor: '../img/cursor.png',
    fontFamily: 'GOTFont',
    titleText: 'Game Of Memory',
    winText: '\u2019ve won this one!',
    titleColor: '#d8b88d',
    buttonColor: '#d8b88d',
    buttonTextColor: '#482427',
    buttonBorder: '#000000',
    textShadow: '2px 2px 2px #000000',
  },
  starwars: {
    name: 'Star Wars',
    cards: ['luke', 'vader', 'yoda', 'leia', 'chewbacca', 'r2d2'],
    imgPath: './src/img/starwars/',
    cardBack: '../img/starwars/card-back.jpg',
    boardMobile: '../img/starwars/board-mobile.jpg',
    board: '../img/starwars/board.jpg',
    cursor: '../img/starwars/cursor.png',
    fontFamily: 'SWFont',
    titleText: 'Star Wars Memory',
    winText: '\u2019ve won this one!',
    titleColor: '#FFE81F',
    buttonColor: '#FFE81F',
    buttonTextColor: '#000000',
    buttonBorder: '#FFE81F',
    textShadow: '2px 2px 4px #0a0a2e',
  },
};
